controller_list:
  - name: fake_elfin_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - elfin_joint1
      - elfin_joint2
      - elfin_joint3
      - elfin_joint4
      - elfin_joint5
      - elfin_joint6
initial:  # Define initial robot poses per group
  - group: elfin_arm
    pose: home